### ISSUE TITLE
[no-ads/v3.2.0.001, Android 11] "individual proxy" only lists system apps; user apps do not appear

### ISSUE THREAD

**Issue by warren-bank** [warren-bank/fork-Android-proxydroid#1]
reported by: @MrCarb0n
status: not yet confirmed

**Comment by warren-bank** [comment]
update: confirmed

target version: [30](https://github.com/warren-bank/fork-Android-proxydroid/blob/no-ads/v3.2.0.001/android-studio-project/constants.gradle#L6)

[Package visibility filtering on Android](https://developer.android.com/training/package-visibility):
* When an app targets Android 11 (API level 30) or higher and queries for information about the other apps that are installed on a device, the system filters this information by default. The limited package visibility reduces the number of apps that appear to be installed on a device, from your app's perspective...

**Comment by MrCarb0n** [comment]
Great! should I share any further information?

**Comment by warren-bank** [comment]
no.. I really appreciate you letting me know that there's a problem, but I have all the info I need. I'll push an update either tonight or tomorrow morning.

**Comment by MrCarb0n** [comment]
thanks.

**Comment by warren-bank** [comment]
Rather than lowering the target version to 29, which is the obvious fix.. I want to try adding the permission instead:
```text
  <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>
```

When I build a new APK, would you mind testing that this permission fixes the problem? I don't have any devices that are running Android 11+.

**Comment by warren-bank** [comment]
[v3.2.0.002](https://github.com/warren-bank/fork-Android-proxydroid/releases/tag/no-ads%2Fv3.2.0.002) adds this permission. Please let me know if it resolves this issue. Thanks.

**Comment by warren-bank** [comment]
for the record: the upstream repo (currently) targets API level [29](https://github.com/madeye/proxydroid/blob/master/app/build.gradle#L11)

**Comment by MrCarb0n** [comment]
> Rather than lowering the target version to 29, which is the obvious fix.. I want to try adding the permission instead:
> 
> ```
>   <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>
> ```
> 
> When I build a new APK, would you mind testing that this permission fixes the problem? I don't have any devices that are running Android 11+.

Yeah, sure..

**Comment by MrCarb0n** [comment]
> [v3.2.0.002](https://github.com/warren-bank/fork-Android-proxydroid/releases/tag/no-ads%2Fv3.2.0.002) adds this permission. Please let me know if it resolves this issue. Thanks.

Yay, this one working fine :D
